### ISSUE TITLE
Misleading text in notification after CLOSE issue

### ISSUE THREAD

**Issue by Bebul** [OpenGrabeso/loctio#10]
I have received window notification when some issue was closed.
Notification section in loctio window has showed the initial text of an issue.
No info, that it was only closed.
There were also multiple comments in this issue, not shown. Only very old issue text shown as fresh.

The issue was:
https://github.com/gamatron/im/issues/25

**Comment by OndrejSpanel** [comment]
Improved last message formatting and added event handling in 32d3109ef73f8e90957b7f65552030e49f9a2fbc
