### ISSUE TITLE
constant CPU usage

### ISSUE THREAD

**Issue by Bebul** [OpenGrabeso/loctio#15]
On my notebook, when closing all my applications except for chrome with 22 tabs, the loctio seems to be the first in the task manager CPU % list, even before chrome.

![image](https://user-images.githubusercontent.com/9265147/86949229-a189e480-c14e-11ea-99e9-d4b9428c92ed.png)

It is java, I am only guessing it is realted to loctio because of the icon used...

**Comment by Bebul** [comment]
A can see also: **WMI Provider Host process**, which may be possibly related.
Read for instance: https://www.howtogeek.com/332838/what-is-the-wmi-provider-host-wmiprvse.exe-and-why-is-it-using-so-much-cpu/

**Comment by OndrejSpanel** [comment]
Use VisualVM to get CPU sampling.
