### ISSUE TITLE
Web client of loctio is loading for ever

### ISSUE THREAD

**Issue by Bebul** [OpenGrabeso/loctio#16]
It often happens, the loctio in web browser stays in loading state and does not show any table with users...

![image](https://user-images.githubusercontent.com/9265147/111004740-db6c5400-8389-11eb-90f6-d29f4757fc6a.png)

**Comment by OndrejSpanel** [comment]
I do not remember even seeing that. Any errors in developer console?

**Comment by Bebul** [comment]
Here you are:
```
Failed to load resource: the server responded with a status of 401 ()
/rest/user//settings:1 Failed to load resource: the server responded with a status of 401 ()
DevTools failed to load SourceMap: Could not load content for https://loctio.appspot.com/frontend/frontend-fastopt.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://loctio.appspot.com/frontend/js-joda.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by Bebul** [comment]
Even in the screenshot there is no USERNAME shown, so maybe token has expired, or something. I have regenerated the token and everything works as usual now.
